### ISSUE TITLE
The use of organ_pseudo

### ISSUE THREAD

**Issue by Luffy03** [MrGiovanni/DiffTumor#1]
Hi, congratulations on your excellent work first! It inspires me a lot!
I want to know what is the use of 'organ_pseudo' in validation. It seems that you are using the organ_pseudo to filter out the tumor predictions, is it correct? 
And how to generate organ_pseudo? Train another organ segmentation model to predict it or directly draw from the real labels?

**Comment by qic999** [comment]
@Luffy03 Thanks for your attention to our work! 

Post-processing operations are commonly used in tumor segmentation. Due to the similarities of tumors across different organs to some extent, it is necessary to filter out tumor predictions in non-target organs. In our study, we use the public pre-trained organ segmentation model from [https://github.com/ljwztc/CLIP-Driven-Universal-Model](https://oai.azure.com/portal/37c0c26b184e4f9fa6748e74cb423302/url) to generate organ pseudo labels. We then use these pseudo labels to ensure that tumor predictions correspond to the correct organ. 

It is acceptable to use other pre-trained organ segmentation models as well. Our experiments are fair since all results are obtained using the same post-processing operations.

**Comment by Luffy03** [comment]
Ok, thanks for your answer.

**Comment by Devil-Ideal** [comment]
> [@Luffy03](https://github.com/Luffy03) Thanks for your attention to our work!
> 
> Post-processing operations are commonly used in tumor segmentation. Due to the similarities of tumors across different organs to some extent, it is necessary to filter out tumor predictions in non-target organs. In our study, we use the public pre-trained organ segmentation model from [https://github.com/ljwztc/CLIP-Driven-Universal-Model](https://oai.azure.com/portal/37c0c26b184e4f9fa6748e74cb423302/url) to generate organ pseudo labels. We then use these pseudo labels to ensure that tumor predictions correspond to the correct organ.
> 
> It is acceptable to use other pre-trained organ segmentation models as well. Our experiments are fair since all results are obtained using the same post-processing operations.

Can you share the psudo labels for validating the performance?
